from typing import Protocol


class InsightsRepository(Protocol):
    data_source: str
    is_gold: bool
    batch_id: str

    async def categories(self) -> list[str]: ...
    async def products(self) -> list[dict]: ...
    async def overview(self, parent_asin: str) -> dict | None: ...
    async def themes(self, parent_asin: str, sentiment: str | None = None, improvement: bool = False) -> dict: ...
    async def theme(self, theme_id: str) -> dict | None: ...
    async def theme_reviews(self, theme_id: str) -> list[dict] | None: ...
    async def batch(self) -> dict: ...
