from __future__ import annotations

from typing import Protocol, Any


class InsightsRepository(Protocol):
    async def health(self) -> dict[str, Any]: ...
    async def categories(self) -> list[str]: ...
    async def products(self, q: str | None, category: str | None, analysis_status: str | None) -> list[dict[str, Any]]: ...
    async def product_overview(self, parent_asin: str) -> dict[str, Any] | None: ...
    async def product_themes(self, parent_asin: str, sentiment: str) -> dict[str, Any] | None: ...
    async def product_improvements(self, parent_asin: str) -> dict[str, Any] | None: ...
    async def theme_detail(self, theme_id: str) -> dict[str, Any] | None: ...
    async def theme_reviews(self, theme_id: str) -> list[dict[str, Any]] | None: ...
    async def batch(self) -> dict[str, Any]: ...
